---
- name: Manage fapolicyd Service on RHEL
  hosts: localhosts
  become: true

  tasks:
    - name: Set fapolicyd to {{ action }}
      ansible.builtin.service:
        name: fapolicyd
        state: "{{ action }}"
